output.json file
113 kumar@destiny ~/workspace/wiki2json > java -jar xxx.jar -c  configFile -g output.json
Error: Unable to access jarfile xxx.jar
114 kumar@destiny ~/workspace/wiki2json > java -jar wiki2json-1.1.0-SNAPSHOT-jar-with-dependencies.jar -c wiki2json.properties -g output.json
log4j:WARN No appenders could be found for logger (de.tudarmstadt.ukp.wikipedia.api.Wikipedia).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2016-12-12 - 18:10:21.777 [main] INFO  net.stargraph.jwpl.Wiki2JSON - Database connection established
2016-12-12 - 18:10:35.894 [main] INFO  net.stargraph.jwpl.Wiki2JSON - Flush 2005 articles to disc (total: 2005)
2016-12-12 - 18:10:37.138 [main] INFO  net.sta